# comp_impact

Notebook to figure out the function

-> into source

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
## Imports

import sys
sys.path.append("..") # Adds the project root to the path

In [4]:
from src.data_exposure import get_exposure
from src.data_hazard import get_haz_dict

In [5]:
haz_dict = get_haz_dict()
haz_list = list(haz_dict.keys())

exposure = get_exposure(hazard_types=haz_list)

In [6]:
from copy import deepcopy
from climada.entity import Exposures

exposure_eigen_gdf = deepcopy(exposure.gdf)

exposure_eigen_gdf["value"] = 1

exposure_eigen_poly = Exposures(exposure_eigen_gdf)

In [7]:
exposure_eigen_poly.gdf

,DDEP_C_COD,DDEP_L_LIB,DREG_L_LIB,value,area,insurance,impf_TC,impf_TP,impf_HL,impf_FL,geometry
0,01,Ain,Auvergne-Rhône-Alpes,1,5762.4,0.30,1,1,1,1,"POLYGON ((6.16845 46.36746, 6.16668 46.37074, ..."
1,02,Aisne,Hauts-de-France,1,7361.7,0.32,1,1,1,1,"POLYGON ((4.25573 49.90398, 4.23694 49.90378, ..."
2,03,Allier,Auvergne-Rhône-Alpes,1,7340.1,0.30,1,1,1,1,"POLYGON ((4.00456 46.32748, 3.99436 46.32765, ..."
3,04,Alpes-de-Haute-Provence,Provence-Alpes-Côte d'Azur,1,6925.2,0.18,1,1,1,1,"POLYGON ((6.96709 44.62287, 6.9539 44.63783, 6..."
4,05,Hautes-Alpes,Provence-Alpes-Côte d'Azur,1,5548.7,0.18,1,1,1,1,"POLYGON ((7.07587 44.68512, 7.07424 44.69209, ..."
...,...,...,...,...,...,...,...,...,...,...,...
91,91,Essonne,Île-de-France,1,1804.4,0.72,1,1,1,1,"POLYGON ((2.58407 48.67715, 2.58038 48.68948, ..."
92,92,Hauts-de-Seine,Île-de-France,1,175.6,0.72,1,1,1,1,"POLYGON ((2.33598 48.93158, 2.33491 48.94154, ..."
93,93,Seine-Saint-Denis,Île-de-France,1,236.2,0.72,1,1,1,1,"POLYGON ((2.6026 48.92936, 2.6024 48.93532, 2...."
94,94,Val-de-Marne,Île-de-France,1,245.0,0.72,1,1,1,1,"POLYGON ((2.61482 48.76112, 2.60645 48.77333, ..."
95,95,Val-d'Oise,Île-de-France,1,1245.9,0.72,1,1,1,1,"POLYGON ((2.59447 49.04714, 2.57243 49.05926, ..."

In [8]:
import climada.util.lines_polys_handler as u_lp
import numpy as np

haz_eai = {}

for haz_type, hazard in haz_dict.items():
    
    ## COMMENT WHY IT WORKS
    
    impact = u_lp.calc_geom_impact(
        exp=exposure_eigen_poly,
        impf_set=hazard["impf_set"],
        haz=hazard["hazard"],
        res=0.05,
        to_meters=False,
        disagg_met=u_lp.DisaggMethod.DIV,
        disagg_val=None,
        agg_met=u_lp.AggMethod.SUM,
    )
    
    eai_exp = np.clip(impact.eai_exp, a_min=0, a_max=1)
    haz_eai[haz_type] = eai_exp


remaining_value = np.ones_like(eai_exp)
for haz_type, eai in haz_eai.items():
   remaining_value *= (1 - eai)
   
commulative_eai = 1 - remaining_value

/Users/arvedluetzen/.pyenv/versions/miniforge3-latest/envs/eth-fs2026-praktikum/lib/python3.12/site-packages/climada/util/lines_polys_handler.py:638: FutureWarning: The 'axis' keyword in DataFrame.groupby is deprecated and will be removed in a future version.
  group = gdf_pnts.groupby(axis=0, level=0)
/Users/arvedluetzen/.pyenv/versions/miniforge3-latest/envs/eth-fs2026-praktikum/lib/python3.12/site-packages/climada/util/lines_polys_handler.py:638: FutureWarning: The 'axis' keyword in DataFrame.groupby is deprecated and will be removed in a future version.
  group = gdf_pnts.groupby(axis=0, level=0)

2026-04-24 09:47:11,602 - climada.util.coordinates - WARNING - Distance to closest centroid is greater than 0.000237 degree for 25727 coordinates.

/Users/arvedluetzen/.pyenv/versions/miniforge3-latest/envs/eth-fs2026-praktikum/lib/python3.12/site-packages/climada/util/lines_polys_handler.py:638: FutureWarning: The 'axis' keyword in DataFrame.groupby is deprecated and will be removed in a future version.
  group = gdf_pnts.groupby(axis=0, level=0)
/Users/arvedluetzen/.pyenv/versions/miniforge3-latest/envs/eth-fs2026-praktikum/lib/python3.12/site-packages/climada/util/lines_polys_handler.py:638: FutureWarning: The 'axis' keyword in DataFrame.groupby is deprecated and will be removed in a future version.
  group = gdf_pnts.groupby(axis=0, level=0)

2026-04-24 09:51:26,847 - climada.util.coordinates - WARNING - Distance to closest centroid is greater than 0.004492 degree for 718 coordinates.

In [77]:
remaining_value

array([0.08069522, 0.        , 0.        , 0.19196496, 0.42933678,
       0.4013724 , 0.        , 0.        , 0.15178043, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.02951233, 0.        ,
       0.        , 0.        , 0.0467619 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.055087  ,
       0.        , 0.01997036, 0.04770632, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.34635338, 0.        ,
       0.09596832, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.13169356, 0.11011269, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.15477143,
       0.23195561, 0.        , 0.        , 0.        , 0.01395954,
       0.        , 0.        , 0.        , 0.5706692 , 0.55478777,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.10072821, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [78]:
aggregated_hazard = deepcopy(exposure.gdf)

aggregated_hazard["commulative_eai"] = commulative_eai

aggregated_hazard

,DDEP_C_COD,DDEP_L_LIB,DREG_L_LIB,value,area,impf_WS,geometry,commulative_eai
0,01,Ain,Auvergne-Rhône-Alpes,0.199,5762.4,1,"POLYGON ((6.16845 46.36746, 6.16668 46.37074, ...",0.919305
1,02,Aisne,Hauts-de-France,0.532,7361.7,1,"POLYGON ((4.25573 49.90398, 4.23694 49.90378, ...",1.000000
2,03,Allier,Auvergne-Rhône-Alpes,0.170,7340.1,1,"POLYGON ((4.00456 46.32748, 3.99436 46.32765, ...",1.000000
3,04,Alpes-de-Haute-Provence,Provence-Alpes-Côte d'Azur,0.025,6925.2,1,"POLYGON ((6.96709 44.62287, 6.9539 44.63783, 6...",0.808035
4,05,Hautes-Alpes,Provence-Alpes-Côte d'Azur,0.017,5548.7,1,"POLYGON ((7.07587 44.68512, 7.07424 44.69209, ...",0.570663
...,...,...,...,...,...,...,...,...
91,91,Essonne,Île-de-France,0.403,1804.4,1,"POLYGON ((2.58407 48.67715, 2.58038 48.68948, ...",1.000000
92,92,Hauts-de-Seine,Île-de-France,NaN,175.6,1,"POLYGON ((2.33598 48.93158, 2.33491 48.94154, ...",1.000000
93,93,Seine-Saint-Denis,Île-de-France,NaN,236.2,1,"POLYGON ((2.6026 48.92936, 2.6024 48.93532, 2....",1.000000
94,94,Val-de-Marne,Île-de-France,0.029,245.0,1,"POLYGON ((2.61482 48.76112, 2.60645 48.77333, ...",1.000000
95,95,Val-d'Oise,Île-de-France,0.381,1245.9,1,"POLYGON ((2.59447 49.04714, 2.57243 49.05926, ...",1.000000

In [66]:
1-haz_eai["WS"]

array([0.08069522, 0.        , 0.        , 0.19196496, 0.42933678,
       0.4013724 , 0.        , 0.        , 0.15178043, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.02951233, 0.        ,
       0.        , 0.        , 0.0467619 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.055087  ,
       0.        , 0.01997036, 0.04770632, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.34635338, 0.        ,
       0.09596832, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.13169356, 0.11011269, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.15477143,
       0.23195561, 0.        , 0.        , 0.        , 0.01395954,
       0.        , 0.        , 0.        , 0.5706692 , 0.55478777,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.10072821, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

## Define Function

In [ ]:
from copy import deepcopy
import numpy as np
from climada.entity import Exposures
import climada.util.lines_polys_handler as u_lp

def comp_impact(haz_dict, exposure):
    """Function that Calculates the Cummulative EAI over multiple Hazard Types

    Args:
        haz_dict (_type_): Dictionary with Hazards and their impact functions
        exposure_template (_type_): A template of how the Exposure Set will look like

    Returns:
        Array: Of Commulative EAI
    """
    
    ## Create an Exposure Map with only 1s
    exposure_eigen_gdf = deepcopy(exposure.gdf)
    exposure_eigen_gdf["value"] = 1
    exposure_eigen_poly = Exposures(exposure_eigen_gdf)
    
    ## Compute the EAI for each Hazard x Impact Function
    haz_eai = {}
    for haz_type, hazard in haz_dict.items():
        
        ## Automatic Computation using Polygons:
        # Dissagg: Splits the Exposure Value into Number of Pixels
        # Agg: Sums up all Damages
        # -> Same effect as not splitting Exposure and then taking a mean
        # SUM((exposure / N) * Impactvalue) = SUM (Exposure * Impactvalue) / N 
        
        impact = u_lp.calc_geom_impact(
            exp=exposure_eigen_poly,
            impf_set=hazard["impf_set"],
            haz=hazard["hazard"],
            res=0.05,
            to_meters=False,
            disagg_met=u_lp.DisaggMethod.DIV,
            disagg_val=None,
            agg_met=u_lp.AggMethod.SUM,
        )
        
        ## Clipping EAI at 1
        ## Make sure Hazard x Impactfunction make sense (not too many >1)
        eai_exp = np.clip(impact.eai_exp, a_min=0, a_max=1)
        haz_eai[haz_type] = eai_exp

    ## Aggregating multiple Hazards together:
    ## (1 - eai_WS) * (1 - eai_FL) * ...
    remaining_value = np.ones_like(eai_exp)
    for haz_type, eai in haz_eai.items():
        remaining_value *= (1 - eai)
    
    ## Going from Relative Remaining Value to EAI
    commulative_eai = 1 - remaining_value
    
    return commulative_eai

In [87]:
exposure = get_exposure(hazard_types=haz_list)

commulative_eai = comp_impact(haz_dict, exposure)

expsoure["commulative_eai"] = commulative_eai

exposure

2026-04-02 14:40:49,197 - climada.util.coordinates - WARNING - Distance to closest centroid is greater than 0.078125 degree for 3 coordinates.

/Users/arvedluetzen/.pyenv/versions/miniforge3-latest/envs/eth-fs2026-praktikum/lib/python3.12/site-packages/climada/util/lines_polys_handler.py:638: FutureWarning: The 'axis' keyword in DataFrame.groupby is deprecated and will be removed in a future version.
  group = gdf_pnts.groupby(axis=0, level=0)

TypeError: Since CLIMADA 2.0, Exposures objects are not subscriptable. Data fields of Exposures objects are accessed using the `gdf` attribute. For example, `expo['value']` is replaced by `expo.gdf['value']`.

### Updated Impact Calc (Disaggregated)

In [24]:
from copy import deepcopy
import numpy as np
from climada.entity import Exposures
import climada.util.lines_polys_handler as u_lp

In [9]:
exp_pnt = u_lp.exp_geom_to_pnt(
    exposure_eigen_poly,
    res=0.05,
    to_meters=False,
    disagg_met=u_lp.DisaggMethod.DIV,
    disagg_val=None,
)
exp_pnt.gdf.head()

/Users/arvedluetzen/.pyenv/versions/miniforge3-latest/envs/eth-fs2026-praktikum/lib/python3.12/site-packages/climada/util/lines_polys_handler.py:638: FutureWarning: The 'axis' keyword in DataFrame.groupby is deprecated and will be removed in a future version.
  group = gdf_pnts.groupby(axis=0, level=0)

    DDEP_C_COD DDEP_L_LIB            DREG_L_LIB    value    area  insurance  \
0 0         01        Ain  Auvergne-Rhône-Alpes  0.00369  5762.4        0.3
  1         01        Ain  Auvergne-Rhône-Alpes  0.00369  5762.4        0.3
  2         01        Ain  Auvergne-Rhône-Alpes  0.00369  5762.4        0.3
  3         01        Ain  Auvergne-Rhône-Alpes  0.00369  5762.4        0.3
  4         01        Ain  Auvergne-Rhône-Alpes  0.00369  5762.4        0.3

     impf_TC  impf_TP  impf_HL  impf_FL  \
0 0        1        1        1        1
  1        1        1        1        1
  2        1        1        1        1
  3        1        1        1        1
  4        1        1        1        1

                                         geometry_orig  \
0 0  POLYGON ((6.16845 46.36746, 6.16668 46.37074, ...
  1  POLYGON ((6.16845 46.36746, 6.16668 46.37074, ...
  2  POLYGON ((6.16845 46.36746, 6.16668 46.37074, ...
  3  POLYGON ((6.16845 46.36746, 6.16668 46.37074, ...
  4  POLYGON ((6.16845 46.36746, 6.16668 46.37074, ...

                     geometry
0 0  POINT (5.63058 45.66149)
  1  POINT (5.68058 45.66149)
  2  POINT (5.58058 45.71149)
  3  POINT (5.63058 45.71149)
  4  POINT (5.68058 45.71149)

In [12]:
from climada.engine import ImpactCalc

# Point-impact
imp_pnt = ImpactCalc(exp_pnt, haz_dict["TP"]["impf_set"], hazard=haz_dict["TP"]["hazard"]).impact(save_mat=True)

In [19]:
imp_pnt.eai_exp.max()

1.1457429717385262e-05

In [ ]:
# Aggregated impact (Note that you need to pass the gdf and not the exposures)
imp_geom = u_lp.impact_pnt_agg(imp_pnt, exp_pnt3.gdf, agg_met=u_lp.AggMethod.SUM)

In [22]:
exposure_eigen_pnt.gdf

      DDEP_C_COD  DDEP_L_LIB            DREG_L_LIB     value    area  \
0  0          01         Ain  Auvergne-Rhône-Alpes  0.003690  5762.4
   1          01         Ain  Auvergne-Rhône-Alpes  0.003690  5762.4
   2          01         Ain  Auvergne-Rhône-Alpes  0.003690  5762.4
   3          01         Ain  Auvergne-Rhône-Alpes  0.003690  5762.4
   4          01         Ain  Auvergne-Rhône-Alpes  0.003690  5762.4
...          ...         ...                   ...       ...     ...
95 54         95  Val-d'Oise         Île-de-France  0.016949  1245.9
   55         95  Val-d'Oise         Île-de-France  0.016949  1245.9
   56         95  Val-d'Oise         Île-de-France  0.016949  1245.9
   57         95  Val-d'Oise         Île-de-France  0.016949  1245.9
   58         95  Val-d'Oise         Île-de-France  0.016949  1245.9

       insurance  impf_TC  impf_TP  impf_HL  impf_FL  \
0  0        0.30        1        1        1        1
   1        0.30        1        1        1        1
   2        0.30        1        1        1        1
   3        0.30        1        1        1        1
   4        0.30        1        1        1        1
...          ...      ...      ...      ...      ...
95 54       0.72        1        1        1        1
   55       0.72        1        1        1        1
   56       0.72        1        1        1        1
   57       0.72        1        1        1        1
   58       0.72        1        1        1        1

                                           geometry_orig  \
0  0   POLYGON ((6.16845 46.36746, 6.16668 46.37074, ...
   1   POLYGON ((6.16845 46.36746, 6.16668 46.37074, ...
   2   POLYGON ((6.16845 46.36746, 6.16668 46.37074, ...
   3   POLYGON ((6.16845 46.36746, 6.16668 46.37074, ...
   4   POLYGON ((6.16845 46.36746, 6.16668 46.37074, ...
...                                                  ...
95 54  POLYGON ((2.59447 49.04714, 2.57243 49.05926, ...
   55  POLYGON ((2.59447 49.04714, 2.57243 49.05926, ...
   56  POLYGON ((2.59447 49.04714, 2.57243 49.05926, ...
   57  POLYGON ((2.59447 49.04714, 2.57243 49.05926, ...
   58  POLYGON ((2.59447 49.04714, 2.57243 49.05926, ...

                       geometry  centr_TC  centr_TP  centr_HL   centr_FL
0  0   POINT (5.63058 45.66149)      1494      1494        -1   94223175
   1   POINT (5.68058 45.66149)      1494      1494        -1   94223197
   2   POINT (5.58058 45.71149)      1493      1493        -1  130016312
   3   POINT (5.63058 45.71149)      1494      1494        -1   94084619
   4   POINT (5.68058 45.71149)      1494      1494        -1   94084641
...                         ...       ...       ...       ...        ...
95 54   POINT (2.1088 49.15868)       597       597        -1    2447087
   55   POINT (2.1588 49.15868)       598       598        -1    2447109
   56   POINT (2.2088 49.15868)       598       598        -1    2447131
   57   POINT (2.3088 49.15868)       598       598        -1    2447176
   58   POINT (1.7088 49.20868)       596       596        -1    2308352

[25740 rows x 16 columns]

In [26]:
import climada.util.lines_polys_handler as u_lp
import numpy as np

haz_eai = {}

exposure_eigen_pnt = u_lp.exp_geom_to_pnt(
    exposure_eigen_poly,
    res=0.05,
    to_meters=False,
    disagg_met=u_lp.DisaggMethod.FIX,
    disagg_val=None,
)

for haz_type, hazard in haz_dict.items():

    impact_pnt = ImpactCalc(
        exposure_eigen_pnt,
        impfset=hazard["impf_set"],
        hazard=hazard["hazard"]
    ).impact(save_mat=True)

    eai = np.clip(impact_pnt.eai_exp, a_min=0, a_max=1)
    haz_eai[haz_type] = eai


## This also has to be done at each point not departement
remaining_value = np.ones_like(eai)
for haz_type, eai in haz_eai.items():
   remaining_value *= (1 - eai)
   
commulative_eai = 1 - remaining_value

commulative_eai

2026-04-24 11:14:12,720 - climada.util.coordinates - WARNING - Distance to closest centroid is greater than 0.000237 degree for 25727 coordinates.
2026-04-24 11:18:31,299 - climada.util.coordinates - WARNING - Distance to closest centroid is greater than 0.004492 degree for 718 coordinates.

array([0.        , 0.        , 0.01023132, ..., 0.00419362, 0.00419362,
       0.00542746])

In [ ]:
exposure_eigen_pnt = u_lp.exp_geom_to_pnt(
    exposure,
    res=pnt_res_m,
    to_meters=True,
    disagg_met=u_lp.DisaggMethod.FIX,
    disagg_val=1,
)

In [ ]:
def comp_impact(haz_dict, exposure_pnt_gdf):
    
    ## Poly -> Eigen Raster Exposure
    exposure_pnt_eigen_gdf = deepcopy(exposure_pnt_gdf)
    exposure_pnt_eigen_gdf["value"] = 1
    exposure_pnt_eigen = Exposures(exposure_pnt_eigen_gdf)
    
    ## Compute EAI per Hazard
    haz_eai = {}
    
    for haz_type, hazard in haz_dict.items():

        impact_pnt = ImpactCalc(
                exposure_pnt_eigen,
                impfset=hazard["impf_set"],
                hazard=hazard["hazard"]
            ).impact(save_mat=True)

        eai = np.clip(impact_pnt.eai_exp, a_min=0, a_max=1)
        haz_eai[haz_type] = eai
    
    ## Aggregate Hazards at each Pixel
    remaining_value = np.ones_like(eai)
    for haz_type, eai in haz_eai.items():
        remaining_value *= (1 - eai)
    
    commulative_eai = 1 - remaining_value
    
    return commulative_eai